security:
  oauth2:
    client:
      clientId: dQFx9IxlOIDfaAPbN3BlDxNF2Pga
      clientSecret: 4TUziGAwG4O5J0j5GOhBJwfb2AUa
      accessTokenUri: http://127.0.0.1:9763/oauth2/token
      userAuthorizationUri: http://127.0.0.1:9763/oauth2/authorize
      token-uri: http://127.0.0.1:9763/oauth2/token
      user-info-uri: http://127.0.0.1:9763/oauth2/userinfo
      jwk-set-uri: http://127.0.0.1:9763/oauth2/jwks
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form